INSERT INTO VIDEO
(SELECT 
VIDEO_ID
, TO_TIMESTAMP(PUBLISHED_AT, 'YYYY-MM-DDTHH:MI:SSZ') PUBLISHED_AT
, TITLE
, DESCRIPTION
, CATEGORY_ID
, CASE 
	WHEN POSITION('H' IN DURATION) <> 0 AND POSITION('M' IN DURATION) <> 0 AND POSITION('S' IN DURATION) <> 0 THEN
		60 * 60 * CAST(SUBSTRING(DURATION, POSITION('T' IN DURATION) + 1, POSITION('H' IN DURATION) - POSITION('T' IN DURATION) - 1) AS INTEGER) +
		60 * CAST(SUBSTRING(DURATION, POSITION('H' IN DURATION) + 1, POSITION('M' IN DURATION) - POSITION('H' IN DURATION) - 1) AS INTEGER) +
		CAST(SUBSTRING(DURATION, POSITION('M' IN DURATION) + 1, POSITION('S' IN DURATION) - POSITION('M' IN DURATION) - 1) AS INTEGER)
	WHEN POSITION('M' IN DURATION) <> 0 AND POSITION('S' IN DURATION) <> 0 THEN
		60 * CAST(SUBSTRING(DURATION, POSITION('T' IN DURATION) + 1, POSITION('M' IN DURATION) - POSITION('T' IN DURATION) - 1) AS INTEGER) +
		CAST(SUBSTRING(DURATION, POSITION('M' IN DURATION) + 1, POSITION('S' IN DURATION) - POSITION('M' IN DURATION) - 1) AS INTEGER)
	WHEN POSITION('M' IN DURATION) <> 0 AND POSITION('S' IN DURATION) = 0 THEN
		60 * CAST(SUBSTRING(DURATION, POSITION('T' IN DURATION) + 1, POSITION('M' IN DURATION) - POSITION('T' IN DURATION) - 1) AS INTEGER)
	WHEN POSITION('M' IN DURATION) = 0 AND POSITION('S' IN DURATION) <> 0 THEN
		CAST(SUBSTRING(DURATION, POSITION('T' IN DURATION) + 1, POSITION('S' IN DURATION) - POSITION('T' IN DURATION) - 1) AS INTEGER)
	ELSE 0
  END DURATION
, DEFINITION
, VIEW_COUNT
, LIKE_COUNT
, DISLIKE_COUNT
, FAVORITE_COUNT
, COMMENT_COUNT
, EMBED_HTML
, CURRENT_TIMESTAMP LAST_MODIFIED
FROM VIDEO_STAGING)
ON CONFLICT ON CONSTRAINT video_pkey
DO UPDATE SET 
PUBLISHED_AT = EXCLUDED.PUBLISHED_AT
, TITLE = EXCLUDED.TITLE
, DESCRIPTION = EXCLUDED.DESCRIPTION
, CATEGORY_ID = EXCLUDED.CATEGORY_ID
, DURATION = EXCLUDED.DURATION
, DEFINITION = EXCLUDED.DEFINITION
, VIEW_COUNT = EXCLUDED.VIEW_COUNT
, LIKE_COUNT = EXCLUDED.LIKE_COUNT
, DISLIKE_COUNT = EXCLUDED.DISLIKE_COUNT
, FAVORITE_COUNT = EXCLUDED.FAVORITE_COUNT
, COMMENT_COUNT = EXCLUDED.COMMENT_COUNT
, EMBED_HTML = EXCLUDED.EMBED_HTML
, LAST_MODIFIED = EXCLUDED.LAST_MODIFIED;