WITH top_10 AS (
	SELECT VIDEO_ID, PUBLISHED_YEAR, TITLE, {{ params.metric }}
	FROM 
	(SELECT
	VIDEO_ID
	, DATE_PART('year', PUBLISHED_AT) PUBLISHED_YEAR
	, ROW_NUMBER() OVER (PARTITION BY DATE_PART('year', PUBLISHED_AT) ORDER BY {{ params.metric }} DESC) RANK_BY_YEAR
	, TITLE
	, {{ params.metric }}
	FROM VIDEO) by_year
	WHERE RANK_BY_YEAR <= 10
	ORDER BY PUBLISHED_YEAR, RANK_BY_YEAR
) 
SELECT JSON_AGG(by_year)
FROM (
	SELECT PUBLISHED_YEAR, ARRAY_AGG(top_10) videos
	FROM top_10
	GROUP BY PUBLISHED_YEAR
) by_year;